### ISSUE TITLE
please provide example of how to run bitcoin-cli against a containerised dockerd

### ISSUE THREAD

**Issue by monkeypants** [amacneil/docker-bitcoin#2]
the container provides `bitcoin`, `bitcoin-cli` and `bitcoin-tx`, and by default runs `bitcoind`.

Assuming have bitcoind running in one container, it would be really helpful if you provide an example of how to connect to it from another container (e.g. `bitcoin-cli`) from another container on the same machine (e.g. docker run command).

**Comment by amacneil** [comment]
Thanks for pointing this out. I have added an example of using `bitcoin-cli` to the readme as part of https://github.com/amacneil/docker-bitcoin/issues/25
