### ISSUE TITLE
latest tag on docker runs 0.13.0 .. it should run 0.14.0

### ISSUE THREAD

**Issue by roswell67** [amacneil/docker-bitcoin#3]
just as the title says. when using the tag latest, 0.13.0 gets run; i've verified this by checking my note version from https://bitnodes.21.co/

**Comment by amacneil** [comment]
Thanks. I set the tag correctly but looks like I needed to trigger a rebuild for it to take effect. Should be fixed shortly.

**Comment by amacneil** [comment]
Fixed!
